# Generated by Django 4.0.3 on 2022-04-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universityimage',
            name='university',
        ),
        migrations.RemoveField(
            model_name='universityimage',
            name='university_en',
        ),
        migrations.RemoveField(
            model_name='universityimage',
            name='university_ru',
        ),
        migrations.RemoveField(
            model_name='universityimage',
            name='university_uz',
        ),
        migrations.RemoveField(
            model_name='country',
            name='image_en',
        ),
        migrations.RemoveField(
            model_name='country',
            name='image_ru',
        ),
        migrations.RemoveField(
            model_name='country',
            name='image_uz',
        ),
        migrations.AddField(
            model_name='post',
            name='date_en',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date'),
        ),
        migrations.AddField(
            model_name='post',
            name='date_ru',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date'),
        ),
        migrations.AddField(
            model_name='post',
            name='date_uz',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date'),
        ),
        migrations.AddField(
            model_name='post',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='News description'),
        ),
        migrations.AddField(
            model_name='post',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='News description'),
        ),
        migrations.AddField(
            model_name='post',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='News description'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Image Cover'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_ru',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Image Cover'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_uz',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Image Cover'),
        ),
        migrations.AddField(
            model_name='post',
            name='slug_en',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='*'),
        ),
        migrations.AddField(
            model_name='post',
            name='slug_ru',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='*'),
        ),
        migrations.AddField(
            model_name='post',
            name='slug_uz',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='*'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_uz',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Title'),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
        migrations.DeleteModel(
            name='UniversityImage',
        ),
    ]
