# Generated by Django 4.0.3 on 2022-03-24 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to='country_images/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='country',
            name='image_ru',
            field=models.ImageField(blank=True, null=True, upload_to='country_images/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='country',
            name='image_uz',
            field=models.ImageField(blank=True, null=True, upload_to='country_images/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='country',
            name='slug_en',
            field=models.SlugField(null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='country',
            name='slug_ru',
            field=models.SlugField(null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='country',
            name='slug_uz',
            field=models.SlugField(null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='degree',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='degree',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='degree',
            name='name_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='postimage',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/', verbose_name='Post image'),
        ),
        migrations.AddField(
            model_name='postimage',
            name='image_ru',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/', verbose_name='Post image'),
        ),
        migrations.AddField(
            model_name='postimage',
            name='image_uz',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/', verbose_name='Post image'),
        ),
        migrations.AddField(
            model_name='postimage',
            name='post_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_images', to='main.post'),
        ),
        migrations.AddField(
            model_name='postimage',
            name='post_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_images', to='main.post'),
        ),
        migrations.AddField(
            model_name='postimage',
            name='post_uz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_images', to='main.post'),
        ),
        migrations.AddField(
            model_name='program',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='program',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='program',
            name='name_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='universityimage',
            name='image_en',
            field=models.ImageField(null=True, upload_to='university_images/', verbose_name='University image'),
        ),
        migrations.AddField(
            model_name='universityimage',
            name='image_ru',
            field=models.ImageField(null=True, upload_to='university_images/', verbose_name='University image'),
        ),
        migrations.AddField(
            model_name='universityimage',
            name='image_uz',
            field=models.ImageField(null=True, upload_to='university_images/', verbose_name='University image'),
        ),
        migrations.AddField(
            model_name='universityimage',
            name='university_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.university'),
        ),
        migrations.AddField(
            model_name='universityimage',
            name='university_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.university'),
        ),
        migrations.AddField(
            model_name='universityimage',
            name='university_uz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.university'),
        ),
    ]
