# Generated by Django 4.0.3 on 2022-03-27 20:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='faculties',
        ),
        migrations.RemoveField(
            model_name='university',
            name='faculties_en',
        ),
        migrations.RemoveField(
            model_name='university',
            name='faculties_ru',
        ),
        migrations.RemoveField(
            model_name='university',
            name='faculties_uz',
        ),
        migrations.RemoveField(
            model_name='university',
            name='grands',
        ),
        migrations.RemoveField(
            model_name='university',
            name='grands_en',
        ),
        migrations.RemoveField(
            model_name='university',
            name='grands_ru',
        ),
        migrations.RemoveField(
            model_name='university',
            name='grands_uz',
        ),
        migrations.AlterField(
            model_name='university',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='university',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='university',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='university',
            name='description_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Description'),
        ),
    ]
