# Generated by Django 4.0.3 on 2022-03-18 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_request_university_alter_request_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='degree',
        ),
        migrations.AddField(
            model_name='request',
            name='degrees',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.degree'),
        ),
    ]
