# Generated by Django 4.0.3 on 2022-03-18 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_request_degree_request_degrees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='degrees',
        ),
        migrations.AddField(
            model_name='request',
            name='ged',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.degree'),
        ),
    ]
