# Generated by Django 4.0.3 on 2022-03-18 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_request_degrees_request_ged'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='ged',
            new_name='degree',
        ),
    ]
