# Generated by Django 4.0.3 on 2022-03-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_ged_request_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='score',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Score'),
        ),
    ]
