# Generated by Django 4.0.3 on 2022-03-23 21:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_request_degree_alter_request_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2022, 3, 23, 21, 21, 25, 287837, tzinfo=utc), verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='universitytranslation',
            name='description',
            field=models.TextField(default=datetime.datetime(2022, 3, 23, 21, 21, 28, 278945, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='universitytranslation',
            name='faculties',
            field=models.TextField(blank=True, verbose_name='Faculties'),
        ),
        migrations.AddField(
            model_name='universitytranslation',
            name='grands',
            field=models.TextField(blank=True, verbose_name='Grands'),
        ),
        migrations.AddField(
            model_name='universitytranslation',
            name='image',
            field=models.ImageField(blank=True, upload_to='university_images/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='universitytranslation',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='universitytranslation',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 3, 23, 21, 21, 30, 53902, tzinfo=utc), max_length=200, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='universitytranslation',
            name='rating',
            field=models.CharField(blank=True, max_length=100, verbose_name='Rating'),
        ),
        migrations.AddField(
            model_name='universitytranslation',
            name='world_rating',
            field=models.CharField(blank=True, max_length=100, verbose_name='World Rating'),
        ),
        migrations.AlterField(
            model_name='request',
            name='degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.degree'),
        ),
        migrations.AlterField(
            model_name='request',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='main.language'),
        ),
        migrations.AlterField(
            model_name='request',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='main.program'),
        ),
        migrations.AlterField(
            model_name='request',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.university'),
        ),
        migrations.AlterField(
            model_name='student',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.country'),
        ),
        migrations.AlterField(
            model_name='student',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.language'),
        ),
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.program'),
        ),
        migrations.AlterField(
            model_name='student',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.request'),
        ),
        migrations.AlterField(
            model_name='student',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.university'),
        ),
        migrations.AlterField(
            model_name='university',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='universities', to='main.country'),
        ),
        migrations.AlterField(
            model_name='universitytranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main.university'),
        ),
    ]
