# Generated by Django 3.2.3 on 2022-04-29 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('surname', models.CharField(blank=True, max_length=200, verbose_name='Surname')),
                ('age', models.CharField(max_length=10, verbose_name='Age')),
                ('country', models.CharField(blank=True, max_length=300, verbose_name='Country')),
                ('lang_certificate', models.BooleanField(blank=True, default=False, verbose_name='Language Certificate')),
                ('score', models.FloatField(blank=True, default=0, null=True, verbose_name='Score')),
                ('phone', models.CharField(max_length=30, verbose_name='Phone Number')),
                ('additional', models.TextField(blank=True, verbose_name='Message')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('degree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.degree')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='main.language')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='main.program')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.university')),
            ],
            options={
                'verbose_name': 'ClientRequest',
                'verbose_name_plural': 'ClientRequest',
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.clientrequest'),
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
